name: Sync template

on:
  # Scheduled workflow
  # schedule:
  #   - cron: "0 0 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  sync-template:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Sync template
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_gh_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: maximilian-hammerl/cv-template
